services:
  # nginx:
  #   build: "./requirements/nginx"
  #   container_name: nginx
  #   restart: always
  #   ports:
  #     - "127.0.0.1:9000:80"

  mariadb:
    environment:
      - WHO=${USER}
    build : "./requirements/mariadb"
    container_name: mariadb
    restart: always

secrets:
  password:
    file: ./password.txt